// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjWOsM_3hqO6C0DVgZd-C1R_1EOVKlzf0',
    appId: '1:933701059702:android:f4a84d60d1656572cb4b57',
    messagingSenderId: '933701059702',
    projectId: 'yotu-clone',
    storageBucket: 'yotu-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr1JGRtm-XxkmJbvd3JgrH2ibMGa-uFrg',
    appId: '1:933701059702:ios:cbe7d5a79fd50670cb4b57',
    messagingSenderId: '933701059702',
    projectId: 'yotu-clone',
    storageBucket: 'yotu-clone.firebasestorage.app',
    androidClientId: '933701059702-krmelh60ad53o773avpv3gtlij9n81nb.apps.googleusercontent.com',
    iosClientId: '933701059702-e7q060os6494kqjjfd4ojtg3vd7vqc78.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

}